jobs:
  - name: start-cluster-development
    plan:
      - .: (( inject meta-dataworks-aws-ch-emr-admin.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
