jobs:
  - name: preprod-stop-full-clusters
    plan:
      - .: (( inject meta-adg-emr-admin.plan.stop-cluster ))
        task: stop-full-clusters
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            SNAPSHOT_TYPE: "full"
