jobs:
  - name: int-clear-dynamodb-row
    plan:
      - .: (( inject meta-cyi-emr-admin.plan.clear-dynamodb-row ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            AWS_ACC: ((aws_account.integration))
            CORRELATION_ID: cyi_1
            DATA_PRODUCT: CYI
