jobs:
  - name: int-start-cluster
    plan:
      - get: aws-ingestion
        trigger: false
      - .: (( inject meta-cyi-emr-admin_emr.plan.terraform-output-ingestion ))
        params:
          TF_WORKSPACE: "integration"
      - .: (( inject meta-cyi-emr-admin_emr.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            AWS_ACC: ((aws_account.integration))
            S3_PREFIX: cyi/2021-05-01
            EXPORT_DATE: "2020-08-13"
