jobs:
  - name: qa-clear-dynamodb-row
    plan:
      - .: (( inject meta-cyi-emr-admin_emr.plan.clear-dynamodb-row ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            AWS_ACC: ((aws_account.qa))
            CORRELATION_ID: cyi_1
            DATA_PRODUCT: CYI
