jobs:
  - name: corporate-load-qa
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-qa
      - get: dataworks-behavioural-framework
        trigger: false
      - .: (( inject meta.plan.terraform-output-ingest ))
        params:
          TF_WORKSPACE: "qa"
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-load ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            ACTION_TAG: "@admin-corporate-data-load"
