jobs:
  - name: stop-cluster-production
    plan:
      - .: (( inject meta-kickstart-adg-emr-admin_emr.plan.stop-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
