jobs:
  - name: prod-start-cluster
    plan:
      - .: (( inject meta-adg-emr-admin.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            S3_PREFIX: businessdata/mongo/ucdata/2021-08-23/full
            EXPORT_DATE: "2021-08-23"
            CORRELATION_ID: b526d8db-805d-5c55-a211-814776f85cca
            SNAPSHOT_TYPE: full
