jobs:
- name: lambda-cleanup-development-job
  plan:
  - get: lambda-cleanup
  - file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.development))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
    task: lambda-cleanup-development
- name: lambda-cleanup-qa-job
  plan:
  - get: lambda-cleanup
  - file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.qa))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
    task: lambda-cleanup-qa
- name: lambda-cleanup-integration-job
  plan:
  - get: lambda-cleanup
  - file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.integration))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
    task: lambda-cleanup-integration
- name: lambda-cleanup-preprod-job
  plan:
  - get: lambda-cleanup
  - file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.preprod))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
    task: lambda-cleanup-preprod
- name: lambda-cleanup-production-job
  plan:
  - get: lambda-cleanup
  - file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.production))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
    task: lambda-cleanup-production
- name: lambda-cleanup-management-job
  plan:
  - get: lambda-cleanup
  - file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.management))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
    task: lambda-cleanup-management
- name: lambda-cleanup-managment-dev-job
  plan:
  - get: lambda-cleanup
  - file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.management-dev))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
    task: lambda-cleanup-management-dev
resources:
- name: lambda-cleanup
  source:
    branch: master
    uri: https://github.com/dwp/dataworks-admin-utils.git
  type: git
