jobs:
  - name: historic-load-integration
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-integration
      - get: aws-ingestion
        trigger: false
      - get: aws-internal-compute
        trigger: false
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: aws-snapshot-sender
        trigger: false
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-ingest ))
          - .: (( inject meta.plan.terraform-output-internal-compute ))
          - .: (( inject meta.plan.terraform-output-snapshot-sender))
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-import ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            ACTION_TAG: "@admin-historic-data-load"
