jobs:
  - name: historic-load-preprod
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-preprod
        - get: aws-ingestion
          trigger: false
        - get: aws-internal-compute
          trigger: false
        - get: aws-dataworks-e2e-framework
          trigger: false
        - get: aws-snapshot-sender
          trigger: false
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "preprod"
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "preprod"
          - .: (( inject meta.plan.terraform-output-snapshot-sender))
            params:
              TF_WORKSPACE: "preprod"
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-import ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            ACTION_TAG: "@admin-historic-data-load"
