jobs:
  - name: historic-load-production
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-production
        - get: dataworks-behavioural-framework
          trigger: false
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-import ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            ACTION_TAG: "@admin_emr-historic-data-load"
            DATA_LOAD_TOPICS: "ALL"
            DATA_LOAD_METADATA_STORE_TABLE: "ucfs"
            DATA_LOAD_S3_SUFFIX: "adb/2020-08-11,calcdb/2020-08-11,cdb/2020-08-11,claimdb/2020-08-12,pdb/2020-08-11,sdb/2020-08-11"
