jobs:
  - name: preprod-start-cluster
    plan:
      - .: (( inject meta-mongo-latest-emr-admin.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            S3_PREFIX: test
            CORRELATION_ID: test
            EXPORT_DATE: "2020-09-24"
