jobs:
  - name: prod-stop-cluster
    plan:
      - .: (( inject meta-cyi-emr-admin.plan.stop-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
