jobs:
  - name: dev-restart-stub-nifi
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.restart-stub-nifi ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: qa-restart-stub-nifi
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.restart-stub-nifi ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: int-restart-stub-nifi
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.restart-stub-nifi ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci


  - name: dev-scale-down-stub-nifi
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.scale-down-stub-nifi ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: qa-scale-down-stub-nifi
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.scale-down-stub-nifi ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: int-scale-down-stub-nifi
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.scale-down-stub-nifi ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: dev-scale-up-stub-nifi
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-snapshot-sender
            trigger: false
      - .: (( inject meta.plan.terraform-output-snapshot-sender ))
        config:
          params:
            TF_WORKSPACE: default
      - .: (( inject meta-manage-ecs-services.plan.scale-up-ecs-service-stub-nifi))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: qa-scale-up-stub-nifi
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-snapshot-sender
            trigger: false
      - .: (( inject meta.plan.terraform-output-snapshot-sender ))
        config:
          params:
            TF_WORKSPACE: default
      - .: (( inject meta-manage-ecs-services.plan.scale-up-ecs-service-stub-nifi))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: int-scale-up-stub-nifi
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-snapshot-sender
            trigger: false
      - .: (( inject meta.plan.terraform-output-snapshot-sender ))
        config:
          params:
            TF_WORKSPACE: default
      - .: (( inject meta-manage-ecs-services.plan.scale-up-ecs-service-stub-nifi))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
