jobs:
  - name: development-restart-k2s3
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.restart-ecs-service ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            ECS_CLUSTER: main
            ECS_SERVICE: stub_ucfs_kafka_to_s3

  - name: qa-restart-k2s3
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-ecs-services.plan.restart-ecs-service ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            ECS_CLUSTER: main
            ECS_SERVICE: stub_ucfs_kafka_to_s3
