jobs:
  - name: production-remove-metadata
    plan:
      - .: (( inject meta-intraday-emr-admin.plan.remove-metadata ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            CLUSTER_ID: ""
