jobs:
  - name: start-cluster-integration
    plan:
      - .: (( inject meta-kickstart-adg-emr-services.plan.start-cluster-without-application ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            START_DT: "2021-03-24"
            END_DT: "2021-03-24"
            LOAD_TYPE: "delta"
            SKIP_FLAG: "False"
            SKIP_MODULES: "vacancy, application"
