jobs:
  - name: prod-clear-dynamodb-row
    plan:
      - .: (( inject meta-mongo-latest-emr-admin.plan.clear-dynamodb-row ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            CORRELATION_ID: bbf37fae-4ddb-5860-9561-262027b37ca7
            DATA_PRODUCT: MONGO_LATEST

