jobs:
  - name: prod-start-cluster
    plan:
      - .: (( inject meta-mongo-latest-emr-admin.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            S3_PREFIX: businessdata/mongo/ucdata/2021-08-31/incremental
            CORRELATION_ID: 475cbe49-1365-59d5-9493-e7ee658d7cb4
            EXPORT_DATE: "2021-08-31"
            SNAPSHOT_TYPE: incremental