jobs:
  - name: prod-start-cluster
    plan:
      - .: (( inject meta-mongo-latest-emr-admin.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            S3_PREFIX: businessdata/mongo/ucdata/2021-07-23/incremental
            CORRELATION_ID: 29e6f95f-e69a-590e-8806-a02beaf2fa89
            EXPORT_DATE: "2021-07-23"
            SNAPSHOT_TYPE: incremental