jobs:
  - name: preprod-remove-metadata
    plan:
      - .: (( inject meta-intraday-emr-admin_emr.plan.remove-metadata ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            CLUSTER_ID: ""
