jobs:
  - name: preprod-trigger-cluster
    plan:
      - .: (( inject meta-intraday-emr-admin_emr.plan.trigger-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
