jobs:
  - name: ami-cleanup-mgmtdev-dryrun
    plan:
    - get: dataworks-admin-utils
    - .: (( inject meta.plan.create-all-aws-profiles ))
    - .: (( inject meta.plan.ami-cleanup-mgmt-dev ))
      config:
        params:
          DRY_RUN: true

  - name: ami-cleanup-mgmtdev
    plan:
    - get: dataworks-admin-utils
      passed:
      - ami-cleanup-mgmtdev-dryrun
    - .: (( inject meta.plan.create-all-aws-profiles ))
    - .: (( inject meta.plan.ami-cleanup-mgmt-dev ))
      config:
        params:
          DRY_RUN: false

  - name: ami-cleanup-mgmt-dryrun
    plan:
    - get: dataworks-admin-utils
    - .: (( inject meta.plan.create-all-aws-profiles ))
    - .: (( inject meta.plan.ami-cleanup-mgmt ))
      config:
        params:
          DRY_RUN: true

  - name: ami-cleanup-mgmt
    plan:
    - get: dataworks-admin-utils
      passed:
        - ami-cleanup-mgmt-dryrun
    - .: (( inject meta.plan.create-all-aws-profiles ))
    - .: (( inject meta.plan.ami-cleanup-mgmt ))
      config:
        params:
          DRY_RUN: true
