meta:
  plan:
    ami-cleanup:
      task: ami-cleanup
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.docker_awscli_repository))
            version: ((dataworks.docker_awscli_version))
            tag: ((dataworks.docker_awscli_version))
        inputs:
          - name: .aws
          - name: dataworks-admin-utils
        params:
          DRY_RUN: true
          AMI_PREFIXES: unset
          AWS_REGION: ((dataworks.aws_region))
          KEEP_MIN: 15
        run:
          path: sh
          args:
            - -exc
            - |
              source /assume-role
              set +x
              for AMI_PREFIX in $AMI_PREFIXES; do
                python3 dataworks-admin-utils/utils/ami-cleanup/ami_cleanup.py --aws-region $AWS_REGION --ami-prefix $AMI_PREFIX --keep-min $KEEP_MIN --dry-run $DRY_RUN
              done

    ami-cleanup-mgmt:
      .: (( inject meta.plan.ami-cleanup ))
      config:
        params:
          AWS_PROFILE: ci-management
          AWS_PROFILE_LIST: ci-development ci-qa ci-integration ci-preprod ci-production ci-management-dev
          AMI_PREFIXES: dw-hardened-ami* dw-general-ami-* dm-untested-hardened-ami-* dw-emr-ami-*

    ami-cleanup-mgmt-dev:
      .: (( inject meta.plan.ami-cleanup-mgmt ))
      config:
        params:
          AWS_PROFILE: ci-management-dev
          AWS_PROFILE_LIST: ci-development ci-qa ci-integration ci-preprod ci-production ci-management
          AMI_PREFIXES: dw-hardened-ami* dw-general-ami-* dm-untested-hardened-ami-* dw-emr-ami-* TEST-dw-hardened-ami-* pr-dw-hardened-ami-*
