jobs:
  - name: pre-prod-stop-msk-kafka-producer-app
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: dataworks-ml-streams-producer
            trigger: false
      - .: (( inject meta-msk-kafka-appl-admin_emr.plan.stop-kafka-producer-app ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
