jobs:
  - name: int-start-cluster
    plan:
      - .: (( inject meta-pt-2-emr-admin_emr.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            AWS_ACC: ((aws_account.integration))
