jobs:
- name: production-import-only
  max_in_flight: 1
  plan:
  - put: meta
    resource: meta-production
  - get: aws-ingestion
    trigger: false
  - get: aws-internal-compute
    trigger: false
  - get: aws-dataworks-e2e-framework
    trigger: false
  - get: aws-snapshot-sender
    trigger: false
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: '((aws_account.production))'
  - aggregate:
    - .: (( inject meta.plan.terraform-output-internal-compute ))
      params:
        TF_WORKSPACE: 'production'
    - .: (( inject meta.plan.terraform-output-ingest ))
      params:
        TF_WORKSPACE: 'production'
    - .: (( inject meta.plan.terraform-output-snapshot-sender ))
      params:
        TF_WORKSPACE: 'production'
  - .: (( inject meta-uc-data-load.plan.uc-data-load ))
    config:
      params:
        AWS_ACC: '((aws_account.production))'
        ACTION_TAG: '@admin-uc-data-load-import-only'
        HISTORIC_IMPORTER_USE_ONE_MESSAGE_PER_PATH: 'true'
        HISTORIC_IMPORTER_SKIP_LATER_THAN_OVERRIDE: '2020-07-10T07:00:00.000'
