jobs:
- name: production-uc-data-load
  max_in_flight: 1
  plan:
  - put: meta
    resource: meta-production
  - get: aws-ingestion
    trigger: false
  - get: aws-internal-compute
    trigger: false
  - get: aws-dataworks-e2e-framework
    trigger: false
  - get: aws-sdx
    trigger: false
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: '((aws_account.production))'
  - aggregate:
    - .: (( inject meta.plan.terraform-output-internal-compute ))
      params:
        TF_WORKSPACE: 'production'
    - .: (( inject meta.plan.terraform-output-ingest ))
      params:
        TF_WORKSPACE: 'production'
    - .: (( inject meta.plan.terraform-output-sdx ))
      params:
        TF_WORKSPACE: 'production'
  - .: (( inject meta-uc-data-load.plan.uc-data-load ))
    config:
      params:
        AWS_ACC: '((aws_account.production))'
        ACTION_TAG: '@admin-uc-data-load'
