jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-qa
      - get: aws-ingestion
        trigger: false
      - get: aws-internal-compute
        trigger: false
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: aws-snapshot-sender
        trigger: false
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "qa"
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "qa"
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: "qa"
      - .: (( inject meta-uc-data-load.plan.uc-data-load ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            ACTION_TAG: "@admin-uc-data-load"
