jobs:
  - name: dev-scale-down-kafka-stub
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-development
          - get: utc-midday-saturdays
            trigger: true
          - get: aws-dataworks-e2e-framework
            trigger: false
      - .: (( inject meta-scale-down-services.plan.scale-down-services ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            AWS_ACC: ((aws_account.development))
            SERVICE_NAME: "kafka-stub"
