jobs:
  - name: dev-scale-down-hdi
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-development
          - get: dataworks-behavioural-framework
            trigger: false
      - .: (( inject meta-scale-down-services.plan.scale-down-services ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            AWS_ACC: ((aws_account.development))
            SERVICE_NAME: "hdi"
