jobs:
  - name: prod-scale-down-htme
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-production
          - get: dataworks-behavioural-framework
            trigger: false
      - .: (( inject meta-scale-down-services.plan.scale-down-services ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            SERVICE_NAME: "htme"
