meta-manage-environments:
  plan:
    manage-environment:
      task: manage-environment
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((docker-awscli.repository))
            version: ((docker-awscli.version))
            tag: ((docker-awscli.version))
        params:
          AWS_DEFAULT_PROFILE: ci
          AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
          AWS_CONFIG_FILE: .aws/config
        run:
          path: sh
          args:
            - -exc
            - |
              set -euo pipefail
              aws lambda invoke --function-name autoshutdown --invocation-type RequestResponse --payload "${PAYLOAD}" --cli-read-timeout 600 output.json
              cat output.json | jq -eC "if .errorMessage? then error(.errorMessage) else true end"
        inputs:
          - name: .aws
