jobs:
  - name: int-start-cluster
    plan:
      - .: (( inject meta-mongo-latest-emr-admin_emr.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            AWS_ACC: ((aws_account.integration))
            S3_PREFIX: test
            CORRELATION_ID: test
            EXPORT_DATE: "2020-09-24"
