jobs:
  - name: stop-emr-cluster-qa
    plan:
      - .: (( inject meta-ch-admin.plan.stop-emr-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
  - name: stop-task-qa
    plan:
      - .: (( inject meta-ch-admin.plan.stop-task ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
