jobs:
  - name: lambda-cleanup-development-job
    plan:
      - get: dataworks-admin-utils
      - .: (( inject meta.plan.lambda-cleanup ))

  - name: lambda-cleanup-qa-job
    plan:
      - get: dataworks-admin-utils
      - .: (( inject meta.plan.lambda-cleanup ))
        config:
          params:
            AWS_ACCOUNT_ID: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: lambda-cleanup-integration-job
    plan:
      - get: dataworks-admin-utils
      - .: (( inject meta.plan.lambda-cleanup ))
        config:
          params:
            AWS_ACCOUNT_ID: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: lambda-cleanup-preprod-job
    plan:
      - get: dataworks-admin-utils
      - .: (( inject meta.plan.lambda-cleanup ))
        config:
          params:
            AWS_ACCOUNT_ID: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci

  - name: lambda-cleanup-production-job
    plan:
      - get: dataworks-admin-utils
      - .: (( inject meta.plan.lambda-cleanup ))
        config:
          params:
            AWS_ACCOUNT_ID: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: lambda-cleanup-management-job
    plan:
      - get: dataworks-admin-utils
      - .: (( inject meta.plan.lambda-cleanup ))
        config:
          params:
            AWS_ACCOUNT_ID: ((aws_account.management))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci

  - name: lambda-cleanup-managment-dev-job
    plan:
      - get: dataworks-admin-utils
      - .: (( inject meta.plan.lambda-cleanup ))
        config:
          params:
            AWS_ACCOUNT_ID: ((aws_account.management-dev))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
