meta:
  plan:
    lambda-cleanup:
      task: lambda-cleanup
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.docker_python_boto_behave_repository))
            tag: ((dataworks.docker_python_boto_behave_version))
        params:
          AWS_ACCOUNT_ID: ((aws_account.development))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
          AWS_REGION: ((dataworks.aws_region))
          AWS_DEFAULT_REGION: ((dataworks.aws_region))
        run:
          dir: dataworks-admin_emr-utils
          path: sh
          args:
            - -exc
            - |
              source /assume-role
              set +x
              ./utils/lambda-cleanup/lambda_prune.py $AWS_ACCOUNT_ID
        inputs:
          - name: dataworks-admin_emr-utils
