resources:
- name: dataworks-admin-utils
  type: git
  source:
    branch: DW-3689-add-lambda-cleanup-util
    uri: https://github.com/dwp/dataworks-admin-utils.git

jobs:
- name: lambda-cleanup-development-job
  plan:
  - get: dataworks-admin-utils
  - task: lambda-cleanup-development
    file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.development))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
- name: lambda-cleanup-qa-job
  plan:
  - get: dataworks-admin-utils
  - task: lambda-cleanup-qa
    file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.qa))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
- name: lambda-cleanup-integration-job
  plan:
  - get: dataworks-admin-utils
  - task: lambda-cleanup-integration
    file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.integration))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
- name: lambda-cleanup-preprod-job
  plan:
  - get: dataworks-admin-utils
  - task: lambda-cleanup-preprod
    file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.preprod))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
- name: lambda-cleanup-production-job
  plan:
  - get: dataworks-admin-utils
  - task: lambda-cleanup-production
    file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.production))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
- name: lambda-cleanup-management-job
  plan:
  - get: dataworks-admin-utils
  - task: lambda-cleanup-management
    file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.management))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
- name: lambda-cleanup-managment-dev-job
  plan:
  - get: dataworks-admin-utils
  - task: lambda-cleanup-management-dev
    file: lambda-cleanup/ci/lambda-cleanup.yml
    params:
      AWS_ACCESS_KEY_ID: ((ci.aws_access_key_id))
      AWS_ACCOUNT_ID: ((aws_account.management-dev))
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ((ci.aws_secret_access_key))
