jobs:
  - name: stop-emr-cluster-preprod
    plan:
      - .: (( inject meta-ch-admin.plan.stop-emr-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
  - name: stop-task-preprod
    plan:
      - .: (( inject meta-ch-admin.plan.stop-task ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
