jobs:
  - name: integration-run-perf-test-peak-kafka-producer-app
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-integration
          - get: dataworks-behavioural-framework
            trigger: false
          - get: dataworks-ml-streams-producer
            trigger: false
      - .: (( inject meta-msk-kafka-appl-admin.plan.perf-test-peak-kafka-producer-app ))
        config:
          params:
            TF_WORKSPACE: default
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
  - name: integration-run-perf-test-soak-kafka-producer-app
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-integration
          - get: dataworks-behavioural-framework
            trigger: false
          - get: dataworks-ml-streams-producer
            trigger: false
      - .: (( inject meta-msk-kafka-appl-admin.plan.perf-test-soak-kafka-producer-app ))
        config:
          params:
            TF_WORKSPACE: default
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
