jobs:
  - name: integration-start-msk-kafka-producer-app
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: dataworks-ml-streams-producer
            trigger: false
      - .: (( inject meta-msk-kafka-appl-admin.plan.start-kafka-producer-app ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
