jobs:
  - name: historic-import-development
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-development
      - get: aws-dataworks-e2e-framework
        trigger: false
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-load ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            ACTION_TAG: "@admin-historic-data-import"
