jobs:
  - name: historic-import-integration
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-integration
        - get: aws-ingestion
          trigger: false
        - get: aws-internal-compute
          trigger: false
        - get: aws-dataworks-e2e-framework
          trigger: false
        - get: aws-snapshot-sender
          trigger: false
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "integration"
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "integration"
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: "integration"
      - .: (( inject meta-hbase-data-ingestion.plan.update-dynamo-db-table-settings ))
        task: update-dynamo-db-table-settings-write-heavy
        params:
          TYPE: "write_heavy"
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
      - .: (( inject meta-hbase-data-ingestion.plan.clear-manifest ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-load ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            ACTION_TAG: "@admin-historic-data-import"
    ensure:
      do:
        - .: (( inject meta-hbase-data-ingestion.plan.update-dynamo-db-table-settings ))
          task: update-dynamo-db-table-settings-normal
          params:
            TYPE: "normal"
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
