jobs:
  - name: historic-import-production-import-only
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-production
        - get: aws-dataworks-e2e-framework
          trigger: false
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-load ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            ACTION_TAG: "@admin-historic-data-import-import-only"
            HISTORIC_IMPORTER_USE_ONE_MESSAGE_PER_PATH: "false"
