jobs:
  - name: historic-import-qa
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-qa
        - get: aws-dataworks-e2e-framework
          trigger: false
      - .: (( inject meta-hbase-data-ingestion.plan.run-data-load ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            ACTION_TAG: "@admin-historic-data-import"
