jobs:
  - name: development-terraform-taint
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-ingestion
            trigger: false
          - get: aws-snapshot-sender
            trigger: false
      - in_parallel:
          - .: (( inject meta-terraform-taint.plan.terraform-taint ))
            input_mapping:
              tfrepo: aws-ingestion
            config:
              params:
                TF_WORKSPACE: "default"
                RESOURCE_ADDRESS_LIST: "aws_ecs_service.kafka_to_hbase_consumer[0] aws_ecs_service.stub_ucfs_kafka_to_s3[0]"
          - .: (( inject meta-terraform-taint.plan.terraform-taint ))
            input_mapping:
              tfrepo: aws-snapshot-sender
            config:
              params:
                TF_WORKSPACE: "default"
                RESOURCE_ADDRESS_LIST: "aws_ecs_service.stub_nifi[0]"
