jobs:
  - name: management-terraform-taint
    max_in_flight: 1
    plan:
      - aggregate:
        - get: aws-internet-egress
          trigger: false
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.management))
      - aggregate:
        - .: (( inject meta-terraform-taint.plan.terraform-taint ))
          input_mapping:
            tfrepo: aws-internet-egress
          config:
            params:
              TF_WORKSPACE: 'management'
              RESOURCE_ADDRESS_LIST: "aws_ecs_service.container_internet_proxy"
