jobs:
  - name: management-dev-terraform-taint
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-internet-egress
            trigger: false
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
      - in_parallel:
          - .: (( inject meta-terraform-taint.plan.terraform-taint ))
            input_mapping:
              tfrepo: aws-internet-egress
            config:
              params:
                TF_WORKSPACE: "default"
                RESOURCE_ADDRESS_LIST: "aws_ecs_service.container_internet_proxy"
