jobs:
  - name: management-dev-terraform-taint
    max_in_flight: 1
    plan:
      - get: aws-internet-egress
        trigger: false
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.management-dev))
      - .: (( inject meta-terraform-taint.plan.terraform-taint ))
        input_mapping:
          tfrepo: aws-internet-egress
        config:
          params:
            TF_WORKSPACE: 'default'
            RESOURCE_NAMES: "aws_ecs_service.container_internet_proxy"
