jobs:
  - name: production-terraform-taint
    max_in_flight: 1
    plan:
      - aggregate:
        - get: aws-ingestion
          trigger: false
        - get: aws-snapshot-sender
          trigger: false
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
      - aggregate:
        - .: (( inject meta-terraform-taint.plan.terraform-taint ))
          input_mapping:
            tfrepo: aws-ingestion
          config:
            params:
              TF_WORKSPACE: 'production'
              RESOURCE_ADDRESS_LIST: "aws_ecs_service.kafka_to_hbase_consumer[0]"

