jobs:
  - name: production-terraform-taint
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: aws-ingestion
            trigger: false
          - get: aws-snapshot-sender
            trigger: false
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
      - in_parallel:
          - .: (( inject meta-terraform-taint.plan.terraform-taint ))
            input_mapping:
              tfrepo: aws-ingestion
            config:
              params:
                TF_WORKSPACE: "production"
                RESOURCE_ADDRESS_LIST: "aws_ecs_service.kafka_to_hbase_consumer[0]"
