jobs:
  - name: integration-scale-up-kafka-stub
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-integration
          - get: utc-2pm-saturdays
            trigger: true
          - get: dataworks-behavioural-framework
            trigger: false
      - .: (( inject meta-scale-up-services.plan.scale-up-services ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            AWS_ACC: ((aws_account.integration))
            SERVICE_NAME: "kafka-stub"
