jobs:
  - name: integration-scale-up-kafka-stub
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-integration
          - get: utc-2pm-saturdays
            trigger: true
          - get: aws-internal-compute
            trigger: false
          - get: aws-ingestion
            trigger: false
          - get: aws-dataworks-e2e-framework
            trigger: false
          - get: dataworks-aws-ingest-consumers
            trigger: false
          - get: aws-snapshot-sender
            trigger: false
      - .: (( inject meta.plan.terraform-bootstrap-ingest-consumers ))
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: integration
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: integration
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: integration
          - .: (( inject meta.plan.terraform-output-ingest-consumers ))
            params:
              TF_WORKSPACE: integration
      - .: (( inject meta-scale-up-services.plan.scale-up-services ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            AWS_ACC: ((aws_account.integration))
            SERVICE_NAME: "kafka-stub"
