jobs:
  - name: preprod-scale-up-htme
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-preprod
          - get: aws-internal-compute
            trigger: false
          - get: aws-ingestion
            trigger: false
          - get: aws-dataworks-e2e-framework
            trigger: false
          - get: dataworks-aws-ingest-consumers
            trigger: false
          - get: aws-snapshot-sender
            trigger: false
      - .: (( inject meta.plan.terraform-bootstrap-ingest-consumers ))
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "preprod"
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "preprod"
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: "preprod"
          - .: (( inject meta.plan.terraform-output-ingest-consumers ))
            params:
              TF_WORKSPACE: "preprod"
      - .: (( inject meta-scale-up-services.plan.scale-up-services ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            SERVICE_NAME: "htme"
