jobs:
- name: qa-scale-up-hdi
  max_in_flight: 1
  plan:
  - aggregate:
    - put: meta
      resource: meta-qa
    - get: aws-internal-compute
      trigger: false
    - get: aws-ingestion
      trigger: false
    - get: aws-dataworks-e2e-framework
      trigger: false
    - get: aws-snapshot-sender
      trigger: false
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: ((aws_account.qa))
  - aggregate:
    - .: (( inject meta.plan.terraform-output-internal-compute ))
      params:
        TF_WORKSPACE: 'qa'
    - .: (( inject meta.plan.terraform-output-ingest ))
      params:
        TF_WORKSPACE: 'qa'
    - .: (( inject meta.plan.terraform-output-snapshot-sender ))
      params:
        TF_WORKSPACE: 'qa'
  - .: (( inject meta-scale-up-services.plan.scale-up-services ))
    config:
      params:
        AWS_ACC: ((aws_account.qa))
        SERVICE_NAME: 'hdi'
