jobs:
  - name: preprod-download-packages
    plan:
      - get: aws-common-infrastructure
        trigger: false
      - .: (( inject meta-ap-dev-emr-admin.plan.terraform-output-common-infrastructure ))
      - .: (( inject meta-ap-dev-emr-admin.plan.download-packages ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))