jobs:
  - name: preprod-stop-incremental-clusters
    plan:
      - .: (( inject meta-adg-emr-services.plan.stop-cluster ))
        task: stop-incremental-clusters
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            SNAPSHOT_TYPE: "incremental"
