jobs:
  - name: start-emr-cluster-integration
    plan:
      - .: (( inject meta-ch-admin.plan.start-emr-cluster))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
  - name: start-task-integration
    plan:
      - .: (( inject meta-ch-admin.plan.start-emr-cluster))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
