jobs:
  - name: start-cluster-integration
    plan:
      - .: (( inject meta-ch-emr-admin.plan.start-cluster))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
