jobs:
  - name: development-restart-k2s3
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta-manage-kafka-connector.plan.restart-kafka-connector ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            ECS_CLUSTER: main
            ECS_SERVICE: stub_ucfs_kafka_to_s3

  - name: qa-restart-k2s3
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
      - .: (( inject meta-manage-kafka-connector.plan.restart-kafka-connector ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            ECS_CLUSTER: main
            ECS_SERVICE: stub_ucfs_kafka_to_s3
