jobs:
  - name: development-scale-down-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta-manage-kafka-connector.plan.scale-down-kafka-connector ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: qa-scale-down-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
      - .: (( inject meta-manage-kafka-connector.plan.scale-down-kafka-connector ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: integration-scale-down-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: '((aws_account.integration))'
      - .: (( inject meta-manage-kafka-connector.plan.scale-down-kafka-connector ))
        config:
          params:
            AWS_ACC: '((aws_account.integration))'
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: preprod-scale-down-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
      - .: (( inject meta-manage-kafka-connector.plan.scale-down-kafka-connector ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: production-scale-down-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: '((aws_account.production))'
      - .: (( inject meta-manage-kafka-connector.plan.scale-down-kafka-connector ))
        config:
          params:
            AWS_ACC: '((aws_account.production))'
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: development-scale-up-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta-manage-kafka-connector.plan.scale-up-kafka-connector ))
      - .: (( inject meta.plan.terraform-output-ingest ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: qa-scale-up-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
      - .: (( inject meta-manage-kafka-connector.plan.scale-up-kafka-connector ))
      - .: (( inject meta.plan.terraform-output-ingest ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: integration-scale-up-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: '((aws_account.integration))'
      - .: (( inject meta-manage-kafka-connector.plan.scale-up-kafka-connector ))
      - .: (( inject meta.plan.terraform-output-ingest ))
        config:
          params:
            AWS_ACC: '((aws_account.integration))'
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: preprod-scale-up-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
      - .: (( inject meta-manage-kafka-connector.plan.scale-up-kafka-connector ))
      - .: (( inject meta.plan.terraform-output-ingest ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer

  - name: production-scale-up-k2hb
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: '((aws_account.production))'
      - .: (( inject meta-manage-kafka-connector.plan.scale-up-kafka-connector ))
      - .: (( inject meta.plan.terraform-output-ingest ))
        config:
          params:
            AWS_ACC: '((aws_account.production))'
            ECS_CLUSTER: main
            ECS_SERVICE: kafka-to-hbase-consumer
