jobs:
  - name: development-shutdown
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
            PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"shutdown\" }" } } ] }'

  - name: qa-shutdown
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
            PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"shutdown\" }" } } ] }'

  - name: integration-shutdown
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
            PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"shutdown\" }" } } ] }'
