jobs:
  - name: development-startup
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: '475593055014'
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
              PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"startup\" }" } } ] }'

  - name: qa-startup
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: '003710426629'
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
              PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"startup\" }" } } ] }'

  - name: integration-startup
    max_in_flight: 1
    plan:
      - .: (( inject meta.plan.create-aws-profiles ))
        config:
          params:
            AWS_ACC: '337387380515'
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
            PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"startup\" }" } } ] }'
