jobs:
  - name: development-startup
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"startup\" }" } } ] }'

  - name: qa-startup
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"startup\" }" } } ] }'

  - name: integration-startup
    max_in_flight: 1
    plan:
      - .: (( inject meta-manage-environments.plan.manage-environment ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            PAYLOAD: '{ "Records": [ { "Sns": { "Message": "{ \"mode\": \"startup\" }" } } ] }'
