jobs:
    - name: int-security-config-monitor
      plan:
        - .: (( inject meta-analytical-env-admin.plan.monitor-security-configs ))
          task: monitor-security-configs
          config:
            params:
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
  