jobs:
  - name: int-cleanup
    plan:
      - .: (( inject meta-analytical-env-admin.plan.clean-security-configs ))
        task: clean-security-configs
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
