jobs:
  - name: preprod-stop-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin_emr.plan.stop-cluster ))
        task: stop-clusters
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
