jobs:
  - name: production-security-config-cleanup
    plan:
      - get: utc-midnight-trigger
        trigger: true
      - .: (( inject meta-analytical-env-admin_emr.plan.clean-security-configs ))
        task: clean-security-configs
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
