jobs:
  - name: qa-start-cluster
    plan:
      - .: (( inject meta-adg-emr-admin_emr.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            AWS_ACC: ((aws_account.qa))
            S3_PREFIX: businessdata/mongo/ucdata/2020-07-06/full/
            EXPORT_DATE: "2020-07-06"
            CORRELATION_ID: test
            SNAPSHOT_TYPE: full
