jobs:
  - name: qa-stop-incremental-clusters
    plan:
      - .: (( inject meta-adg-emr-admin.plan.stop-cluster ))
        task: stop-incremental-clusters
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            SNAPSHOT_TYPE: "incremental"
