jobs:
- name: qa-uc-list-snapshots
  max_in_flight: 1
  plan:
  - put: meta
    resource: meta-qa
  - get: aws-ingestion
    trigger: false
  - get: aws-internal-compute
    trigger: false
  - get: aws-dataworks-e2e-framework
    trigger: false
  - get: aws-sdx
    trigger: false
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: ((aws_account.qa))
  - .: (( inject meta.plan.terraform-output-internal-compute ))
    params:
      TF_WORKSPACE: 'qa'
  - .: (( inject meta.plan.terraform-output-ingest ))
    params:
      TF_WORKSPACE: 'qa'
  - .: (( inject meta.plan.terraform-output-sdx ))
    params:
      TF_WORKSPACE: 'qa'
  - .: (( inject meta-uc-list-snapshots.plan.uc-list-snapshots ))
    config:
      params:
        AWS_ACC: ((aws_account.qa))
