jobs:
  - name: dev-start-msk-kafka-producer-app
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: dataworks-ml-streams-producer
            trigger: false
      - .: (( inject meta-msk-kafka-appl-admin_emr.plan.start-kafka-producer-app ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
