jobs:
  - name: production-send-snapshots
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-production
      - get: aws-ingestion
        trigger: false
      - get: aws-internal-compute
        trigger: false
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: aws-snapshot-sender
        trigger: false
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "production"
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "production"
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: "production"
      - .: (( inject meta-send-snapshots.plan.send-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            SEND_SNAPSHOTS_DATE_OVERRIDE: "2020-06-02"
            SEND_SNAPSHOTS_TOPICS_OVERRIDE: "ALL"
            E2E_FEATURE_TAG_FILTER: "@admin-send-full-snapshots-to-crown"
