resources:
  - name: every-60-minutes
    type: time
    source: { interval: 60m }

jobs:
  - name: production-nifi-heartbeat
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-production
        - get: every-60-minutes
          trigger: true
        - get: aws-snapshot-sender
          trigger: false
        - get: aws-internal-compute
          trigger: false
        - get: dataworks-behavioural-framework
          trigger: false

      - .: (( inject meta-send-snapshots.plan.terraform-output-internal-compute ))
        config:
          params:
            TF_WORKSPACE: "production"

      - .: (( inject meta-send-snapshots.plan.upload-heartbeat-files ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

      - .: (( inject meta-send-snapshots.plan.send-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            SEND_SNAPSHOTS_DATE_OVERRIDE: "NIFI_HEARTBEAT"
            SEND_SNAPSHOTS_TOPICS_OVERRIDE: "db.nifi-heartbeat.production"
            SEND_SNAPSHOTS_REPROCESS_FILES_OVERRIDE: "true"
            SNAPSHOT_SENDER_SCALE_UP_OVERRIDE: 1
            E2E_FEATURE_TAG_FILTER: "@admin-send-full-snapshots-to-crown"
