jobs:
- name: production-send-snapshots
  max_in_flight: 1
  plan:
  - put: meta
    resource: meta-production
  - get: aws-ingestion
    trigger: false
  - get: aws-internal-compute
    trigger: false
  - get: aws-dataworks-e2e-framework
    trigger: false
  - get: aws-sdx
    trigger: false
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: '((aws_account.production))'
  - aggregate:
    - .: (( inject meta.plan.terraform-output-internal-compute ))
      params:
        TF_WORKSPACE: 'production'
    - .: (( inject meta.plan.terraform-output-ingest ))
      params:
        TF_WORKSPACE: 'production'
    - .: (( inject meta.plan.terraform-output-sdx ))
      params:
        TF_WORKSPACE: 'production'
  - .: (( inject meta-send-snapshots.plan.send-snapshots ))
    config:
      params:
        AWS_ACC: '((aws_account.production))'
        SEND_SNAPSHOTS_DATE_OVERRIDE: '2020-04-26'
        SEND_SNAPSHOTS_TOPICS_OVERRIDE: 'db.accepted-data.overlappingBenefit,db.accepted-data.gracePeriod,db.accepted-data.capital,db.accepted-data.childrenCircumstances,db.accepted-data.housingEntitlement,db.accepted-data.healthAndDisabilityCircumstances,db.accepted-data.employmentCircumstances,db.accepted-data.guardiansAllowance,db.accepted-data.healthCircumstances,db.accepted-data.personDetails,db.accepted-data.bankDetails,db.accepted-data.otherBenefit,db.accepted-data.apa,db.accepted-data.calculateDeductions,db.accepted-data.address,db.accepted-data.ineligiblePartner,db.accepted-data.pregnancy,db.accepted-data.workAndEarningsCircumstances,db.accepted-data.carersAllowance,db.accepted-data.supportForMortgageInterest,db.accepted-data.terminalIllness,db.accepted-data.childElementEligibility,db.accepted-data.otherIncome,db.accepted-data.nationality,db.accepted-data.carerCircumstances,db.accepted-data.previousEarnings,db.accepted-data.childcare,db.accepted-data.educationCircumstances,db.accepted-data.partnerQuestion,db.accepted-data.housingCircumstances,db.accepted-data.workCapabilityAssessmentDecision'
