jobs:
  - name: qa-send-snapshots
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-qa
      - get: dataworks-behavioural-framework
        trigger: false
      - .: (( inject meta-send-snapshots.plan.send-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            E2E_FEATURE_TAG_FILTER: "@admin-send-full-snapshots-to-crown"
