jobs:
  - name: start-emr-cluster-production
    plan:
      - .: (( inject meta-ch-admin.plan.start-emr-cluster))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
  - name: start-task-production
    plan:
      - .: (( inject meta-ch-admin.plan.start-task))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
