jobs:
  - name: update-pipeline
    plan:
      - get: dataworks-admin-utils
        resource: dataworks-admin-utils-update-pipeline
        trigger: true
      - .: (( inject meta.plan.update-pipeline ))
        config:
          params:
            aviator_filename: aviator-mongo-latest-emr-admin.yml

