jobs:
  - name: preprod-start-cluster
    plan:
      - .: (( inject meta-pd-2-emr-admin.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
