jobs:
  - name: integration-generate-full-snapshots
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-integration
      - get: aws-ingestion
        trigger: false
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: dataworks-aws-ingest-consumers
        trigger: false
      - get: aws-internal-compute
        trigger: false
      - get: aws-snapshot-sender
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap-ingest-consumers ))
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "integration"
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "integration"
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: "integration"
          - .: (( inject meta.plan.terraform-output-ingest-consumers ))
            params:
              TF_WORKSPACE: "integration"
      - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            E2E_FEATURE_TAG_FILTER: admin-generate-full-snapshots-with-completion-status-poller
            GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: "db.matchingService.managementInformation,db.core.contract,db.accepted-data.address,db.agent-core.agent,db.agent-core.agentToDo,db.agent-core.team,db.core.claimant"
            GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: false
            GENERATE_SNAPSHOTS_TRIGGER_ADG_OVERRIDE: true
