jobs:
- name: integration-generate-incremental-snapshots
  max_in_flight: 1
  plan:
  - put: meta
    resource: meta-integration
  - get: aws-ingestion
    trigger: false
  - get: aws-dataworks-e2e-framework
    trigger: false
  - get: aws-internal-compute
    trigger: false
  - get: aws-snapshot-sender
    trigger: false
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: '((aws_account.integration))'
  - aggregate:
    - .: (( inject meta.plan.terraform-output-internal-compute ))
      params:
        TF_WORKSPACE: 'integration'
    - .: (( inject meta.plan.terraform-output-ingest ))
      params:
        TF_WORKSPACE: 'integration'
    - .: (( inject meta.plan.terraform-output-snapshot-sender ))
      params:
        TF_WORKSPACE: 'integration'
  - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
    config:
      params:
        AWS_ACC: '((aws_account.integration))'
        SNAPSHOT_TYPE: incremental
        GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: 'ALL'
        GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: false
