jobs:
  - name: preprod-generate-full-snapshots
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-preprod
      - get: aws-ingestion
        trigger: false
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: aws-internal-compute
        trigger: false
      - get: aws-snapshot-sender
        trigger: false
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "preprod"
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "preprod"
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: "preprod"
      - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            E2E_FEATURE_TAG_FILTER: admin-generate-full-snapshots-with-completion-status-poller
            GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: "db.work-search-core.job"
            GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: true
            GENERATE_SNAPSHOTS_REPROCESS_FILES_OVERRIDE: true
            GENERATE_SNAPSHOTS_TRIGGER_ADG_OVERRIDE: true
