jobs:
  - name: preprod-generate-full-snapshots
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-preprod
      - get: dataworks-behavioural-framework
        trigger: false
      - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            E2E_FEATURE_TAG_FILTER: admin-generate-full-snapshots
            GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: "ALL"
            GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: false
            GENERATE_SNAPSHOTS_REPROCESS_FILES_OVERRIDE: true
            GENERATE_SNAPSHOTS_EXPORT_DATE_OVERRIDE: "2021-01-02" 
            GENERATE_SNAPSHOTS_START_TIME_OVERRIDE: "2017-07-01T00:00:00.000" # MUST NEVER BE BEFORE JULY 2017
            GENERATE_SNAPSHOTS_END_TIME_OVERRIDE: "2021-01-02T00:00:00.000"
            GENERATE_SNAPSHOTS_TRIGGER_ADG_OVERRIDE: true
