jobs:
  - name: production-nightly-generate-and-send
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-production
      - get: daily-at-midnight
        trigger: true
      - get: aws-ingestion
        trigger: false
      - get: aws-dataworks-e2e-framework
        trigger: false
      - get: aws-internal-compute
        trigger: false
      - get: aws-snapshot-sender
        trigger: false
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: "production"
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: "production"
          - .: (( inject meta.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: "production"
      - .: (( inject meta-generate-snapshots.plan.clear-s3-prefix))
        config:
          params:
            AWS_ROLE_ARN: "arn:aws:iam::((aws_account.production)):role/ci"
            TYPE: "htme_output"
      - .: (( inject meta-generate-snapshots.plan.clear-s3-prefix))
        config:
          params:
            AWS_ROLE_ARN: "arn:aws:iam::((aws_account.production)):role/ci"
            TYPE: "htme_manifest"
      - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
        config:
          params:
            AWS_ROLE_ARN: "arn:aws:iam::((aws_account.production)):role/ci"
            SNAPSHOT_TYPE: full
            GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: "ALL"
            GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: true
            GENERATE_SNAPSHOTS_REPROCESS_FILES_OVERRIDE: true
      - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
        config:
          params:
            AWS_ROLE_ARN: "arn:aws:iam::((aws_account.production)):role/ci"
            SNAPSHOT_TYPE: incremental
            GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: "ALL"
            GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: true
            GENERATE_SNAPSHOTS_REPROCESS_FILES_OVERRIDE: true
