jobs:
  - name: production-generate-full-snapshots
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-production
      - get: dataworks-behavioural-framework
        trigger: false
      - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            E2E_FEATURE_TAG_FILTER: admin-generate-full-snapshots
            GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: "ALL"
            GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: false
