jobs:
  - name: qa-generate-incremental-snapshots
    max_in_flight: 1
    plan:
      - put: meta
        resource: meta-qa
      - get: aws-dataworks-e2e-framework
        trigger: false
      - .: (( inject meta-generate-snapshots.plan.generate-snapshots ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            E2E_FEATURE_TAG_FILTER: admin-generate-incremental-snapshots
            GENERATE_SNAPSHOTS_TOPICS_OVERRIDE: "ALL"
            GENERATE_SNAPSHOTS_TRIGGER_SNAPSHOT_SENDER_OVERRIDE: false
            GENERATE_SNAPSHOTS_USE_POLLER_OVERRIDE: false
