jobs:
  - name: dev-stop-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin_emr.plan.stop-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: dev-stop-user-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin_emr.plan.stop-user-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: dev-stop-external-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin_emr.plan.stop-external-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: dev-stop-uc-lab-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin_emr.plan.stop-uc-lab-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: dev-stop-waiting
    plan:
      - get: every-2h
        trigger: true
      - .: (( inject meta-analytical-env-admin_emr.plan.stop-waiting-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
        
