jobs:
  - name: qa-stop-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin.plan.stop-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: qa-stop-user-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin.plan.stop-user-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: qa-stop-external-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin.plan.stop-external-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: qa-stop-uc-lab-batch-cluster
    plan:
      - get: aws-analytical-env
        trigger: false
      - .: (( inject meta-analytical-env-admin.plan.stop-uc-lab-batch-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: qa-stop-waiting
    plan:
      - get: every-2h
        trigger: true
      - .: (( inject meta-analytical-env-admin.plan.stop-waiting-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
        
