jobs:
  - name: qa-remove-metadata
    plan:
      - .: (( inject meta-intraday-emr-admin_emr.plan.remove-metadata ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            AWS_ACC: ((aws_account.qa))
            CLUSTER_ID: ""
